const mongoose = require("mongoose");

const messageSchema = new mongoose.Schema(
  {
    // ============================================
    // MESSAGE IDENTIFIER
    // ============================================

    messageId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
    },

    // ============================================
    // CLIENT MESSAGE IDENTIFIER
    //
    // Generated by the client.
    //
    // This is important for offline messages and
    // retry protection.
    // ============================================

    clientMessageId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
    },

    // ============================================
    // SENDER
    // ============================================

    senderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    // ============================================
    // RECEIVER
    // ============================================

    receiverId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    // ============================================
    // MESSAGE CONTENT
    //
    // Phase 1 stores normal message text.
    //
    // E2EE can be introduced later without
    // changing the overall message architecture.
    // ============================================

    text: {
      type: String,
      required: true,
      trim: true,
      maxlength: 10000,
    },

    // ============================================
    // MESSAGE STATUS
    // ============================================

    status: {
      type: String,
      enum: [
        "pending",
        "sent",
        "delivered",
        "read",
        "failed",
      ],
      default: "sent",
      index: true,
    },

    // ============================================
    // DELIVERY TIMESTAMP
    // ============================================

    deliveredAt: {
      type: Date,
      default: null,
    },

    // ============================================
    // READ TIMESTAMP
    // ============================================

    readAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

// ============================================
// CONVERSATION INDEX
//
// Makes fetching messages between two users
// significantly faster.
// ============================================

messageSchema.index({
  senderId: 1,
  receiverId: 1,
  createdAt: 1,
});

// Reverse direction is also queried.
messageSchema.index({
  receiverId: 1,
  senderId: 1,
  createdAt: 1,
});

// ============================================
// USER TIMELINE INDEX
//
// Useful for future synchronization.
// ============================================

messageSchema.index({
  receiverId: 1,
  createdAt: 1,
});

messageSchema.index({
  senderId: 1,
  createdAt: 1,
});

// ============================================
// MODEL
// ============================================

const Message = mongoose.model(
  "Message",
  messageSchema
);

module.exports = Message;